from glob import glob
import os

metadata_files = glob("../src/PSO/PSOSetup/FMG_FMG_*.dat")
SAMPLES = [os.path.basename(f).replace("FMG_FMG_", "").replace(".dat", "") for f in metadata_files]

configfile: "slurm/config.yaml"

rule all:
    input:
        expand("../src/PSO/OptimizationResults/FMG_FMG/Opt_FMG_{sample}.mat", sample=SAMPLES)

rule run_pso_optimization_fmg:
    input:
        "../src/PSO/PSOSetup/FMG_FMG_{metadata}.dat"
    output:
        "../src/PSO/OptimizationResults/FMG_FMG/Opt_FMG_{metadata}.mat",
    params:
        matlab_function = "main_loop_hpcc_function",
    log:
        "logs/run_pso_fmg_{metadata}.log"
    # resources:
    #     runtime=config["default-resources"]["runtime"],
    #     mem_mb=config["default-resources"]["mem_mb"],
    #     cpu_per_task=config["default-resources"]["cpus_per_task"]
    shell:
        """
        bash run_matlab.sh ../src/PSO "{params.matlab_function}('FMG_FMG_{wildcards.metadata}')" "../../workflow/{log}"
        """