name: MATLAB Tests

on: [push, pull_request]

jobs:
  matlab-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      
      - name: Run MATLAB Tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: .
          test-results-junit: test-results/results.xml
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/results.xml
